project:
  type: website
  render:
    - "*.qmd"
  
website:
  title: "Reclamation"
  navbar:
    left:
      - abandoned_wells.qmd
      - leaf_process.qmd
      - gee_filtering.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
